language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.5
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -r test_project/requirements.txt --use-mirrors
  - pip install -q -e . --use-mirrors

script:
  - make test
